---

# content folder - {{ home }}/{{ azerothcore_folder }}, this is optional and can be left blank
# to create folders in the home-dir directly. Or it can be multiple folders.
azerothcore_folder: "azerothcore-wotlk"

# $HOME
home: "{{ ansible_env.HOME }}"
root: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}"
temp: "{{ home }}/{{ azerothcore_folder }}/temp"
sql_dir: "{{ home }}/{{ azerothcore_folder }}/sql"

# realmlist - the address of where your server runs and the name for it
azerothcore_realmlist_name: "My Realm" 
azerothcore_realmlist_ip: "127.0.0.1" # world server binds to this
azerothcore_realmlist_local_ip: "127.0.0.1"
azerothcore_realmlist_port: "8085" # world server binds to this
azerothcore_realmlist_auth_port: "3724" # world server binds to this
azerothcore_realmlist_id: "1" # world server binds to this


# Where the source code is downloaded to
azerothcore_source: "source"

# Server folder name - this will be used for the symlink to the current live version
# as well as the reference name suffixed by the commit tag
azerothcore_server: "acore"

# database information - for now only tested using "localhost"
azerothcore_db_server: "localhost"
azerothcore_db_port: "3306"
azerothcore_db_user: "azerothcore"
# TODO: we should be using Ansible vault here
azerothcore_db_password: "azerothcore"

# the 3 databases used
azerothcore_db_characters: "acore_characters"
azerothcore_db_auth: "acore_auth"
azerothcore_db_world: "acore_world"


# enable server as a service (systemd), value can be "enable" or "disable"
azerothcore_service: "enable"

# where to get the source code from
azerothcore_git: "https://github.com/azerothcore/azerothcore-wotlk.git"

# discard changes to the repo, yes or no
azerothcore_git_force: "yes"

# the build to check out from Git
azerothcore_branch: "master"
azerothcore_server_release: "{{azerothcore_branch}}"

# compile tools (map-extraction etc.), '1' (true) or '0' (false)
azerothcore_tools: "1"

# enable debugging (recommended for development only), '1' (true) or '0' (false)
azerothcore_debug: "0"

# compiler to use, you can reference whatever you prefer
azerothcore_compiler: "/usr/bin/clang"
azerothcore_compiler_xx: "/usr/bin/clang++"

# cronjob for backup, multiple values can be listed such as "3,5,12" etc., leave empty to not setup backup
azerothcore_cron_minute: "0"
azerothcore_cron_hour: "7"

# Modules you want Ansible to download for you
azerothcore_modules:
  - 

# The Eluna LUA scripts you want to copy up
# These must be present at ./files/
azerothcore_scripts:
  - crazy_chickens/chicken.lua
  - crazy_chickens/magic_chicken.lua
  - crazy_chickens/cat.lua