---

- hosts: all
  become: no

  pre_tasks:
    - name: Ensure all target directories are set up on the remote server
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ temp }}"
        - "{{ sql_dir }}"
        - "{{ root }}/bin/lua_scripts"

    - name: Set up the databases - world, auth, characters
      import_role:
        name: azerothcore-database
        tasks_from: init

  roles:
    - role: azerothcore
    - role: azerothcore-database
  
  post_tasks:   
    - name: Start the services
      systemd_service:
        name: "{{ item }}"
        state: restarted
        scope: user
      loop:
        - authserver
        - worldserver
  