---

- hosts: all
  become: no

  pre_tasks:
    - name: Ensure all target directories are set up on the remote server
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ temp }}"
        - "{{ sql_dir }}"

    - name: Set up the base database
      import_role:
        name: azerothcore-database
        tasks_from: init

  roles:
    - role: azerothcore
    - role: azerothcore-database
  
  post_tasks:
    # - name: Update the realmlist database with our realm data
    #   import_role:
    #     name: azerothcore-database
    #     tasks_from: realmlist
    
    # - name: Run any custom SQL
    #   import_role:
    #     name: azerothcore-database
    #     tasks_from: custom
    
    - name: Start the services
      systemd_service:
        name: "{{ item }}"
        state: restarted
        scope: user
      loop:
        - authserver
        - worldserver
  