---

- hosts: all
  become: no

  pre_tasks:
    # - name: Get the AzerothCore source on disk before we do anything
    #   import_role:
    #     name: azerothcore
    #     tasks_from: source
    - name: Get the AzerothCore source on disk before we do anything
      import_role:
        name: azerothcore-database
        tasks_from: init

  roles:
    - role: azerothcore
  
  post_tasks:
    - name: Get the AzerothCore source on disk before we do anything
      import_role:
        name: azerothcore-database
        tasks_from:
          - realmlist
          - custom
    
    - name: Start the services
      systemd_service:
        name: "{{ item }}"
        state: started
        scope: user
      loop:
        - authserver
        - worldserver
  
