---

- hosts: all
  become: true
  tasks: 
    - name: Restart the World Server
      systemd_service:
        name: worldserver
        state: restarted
      tags:
        - worldserver
    
    - name: Restart the Auth Server
      systemd_service:
        name: authserver
        state: restarted
      tags:
        - authserver
