---

- name: Update packages and install dependencies
  include_tasks: "tasks/packages.yml"
  tags:
    - packages

- name: Set up our AzerothCore user
  include_tasks: "tasks/user.yml"
  tags:
    - user

- name: Set up sudoers for our AzerothCore Linux user
  include_tasks: "tasks/sudoers.yml"
  tags:
    - sudoers

- name: Setup MySQL with our user
  include_tasks: "tasks/mysql.yml"
  tags:
    - mysql

- name: Include task for systemd
  include_tasks: "tasks/systemd.yml"
  tags:
    - systemd
