---

- name: Update packages and install dependencies
  include_tasks: "tasks/packages.yml"
  tags:
    - packages

- name: Set up our AzerothCore user
  include_tasks: "tasks/user.yml"
  tags:
    - user

- name: Setup MySQL with our user
  include_tasks: "tasks/mysql.yml"
  tags:
    - mysql
