---

- name: Create the required directory for our binaries and configs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin"
    - "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules"

- name: Download the binaries
  ansible.builtin.get_url:
    url: "https://github.com/Upload-Academy/azerothcore-ansible/releases/download/v0.1.0/{{ item }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/"
    mode: '0770'
  loop:
    - "worldserver"
    - "authserver"
