---

- name: Move our compile script into place
  template:
    src: compile.sh
    dest: "{{ home }}/{{ azerothcore_folder }}/compile.sh"
    mode: "0775"
  tags:
    - build

- name: Run our compile script
  shell: "./compile.sh > compile.log"
  args:
    chdir: "{{ home }}/{{ azerothcore_folder }}/"
  tags:
    - build
