---

- name: Create the database directory
  file:
    path: "{{ home }}/{{ azerothcore_folder }}/database/"
    state: directory

- name: Database related files
  template:
    src: "sql/{{ item }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/database/"
  with_items:
    - auth_custom.sql

# Only run this if there is no previous server aka a new install
- name: Run custom SQL against database
  shell: "mysql -u {{ azerothcore_db_user }} --password={{ azerothcore_db_password }} {{ azerothcore_db_auth }} < {{ home }}/{{ azerothcore_folder }}/database/auth_custom.sql"
