---

#####################
# Dependancies
#####################

# ./acore.sh install-deps

- name: Install package dependancies
  apt:
    name:
      - build-essential
      - clang
      - cmake
      - default-libmysqlclient-dev
      - git
      - libace-dev
      - libboost-all-dev
      - libbz2-dev
      - libncurses-dev
      - libreadline-dev
      - libreadline8
      - libssl-dev
      - make
      - mysql-server
      - screen # for running the world- and authserver
      - sudo
      - unzip # for extra modules etc.
  become: true
  when: ansible_os_family == 'Debian' 

- name: Install package dependancies < 22.04
  apt:
    name:
      - libace-6.*
  become: true
  when: ansible_os_family == 'Debian' and ansible_distribution_version < "22.04"

- name: Install package dependancies >= 22.04
  apt:
    name:
      - libace-7.*
  become: true
  when: ansible_os_family == 'Debian' and ansible_distribution_version >= "22.04"

#####################
# User for the project
#####################

- name: Create user
  user:
    name: "{{ azerothcore_user }}"
    home: "/home/{{ azerothcore_user }}"
    shell: "/bin/bash"
    state: present
    password: "{{ azerothcore_user_password }}"
    groups: "sudo"
  become: true
  register: user_created

- name: Allow various sudo commands
  template:
    src: "etc/sudoers.d/azerothcore_user"
    dest: "/etc/sudoers.d/{{ azerothcore_user }}"
    owner: "root"
    group: "root"
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
  become: true

- name: Allow using MySQL without typing in passwords
  template:
    src: "sql/dot.my.cnf"
    dest: "/home/{{ azerothcore_user }}/.my.cnf"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"
    mode: 0600
  become: true

#####################
# The game client location
#####################

# - name: Create base folder
#   file:
#     path: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}"
#     mode: "0755"
#     state: "directory"
#     owner: "{{ azerothcore_user }}"
#     group: "{{ azerothcore_user }}"
#   become: true

# - name: Check if the client folder exists
#   stat:
#     path: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_wow_client }}"
#   become: true
#   register: client_folder

# - name: Notify of problems
#   debug:
#     msg: "You need to place the client in folder '/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_wow_client }}'"
#   when: client_folder.stat.exists == false

#####################
# If the local user was just created, we will exit
#####################

# - name: Information if we need to restart Ansible or not
#   debug:
#     msg: "User '{{ azerothcore_user }}' just created or updated. Please run the playbook again as user '{{ azerothcore_user }}'!"
#   when: user_created.changed

# - meta: end_play
#   when: user_created.changed or client_folder.stat.exists == false
