---

- name: Include task for downloading the AzerothCore source
  include_tasks: "tasks/source.yml"
  tags:
    - source

- name: Include task for downloading the AzerothCore modules
  include_tasks: "tasks/modules.yml"
  tags:
    - modules

- name: Include task for building
  include_tasks: "tasks/build.yml"
  tags:
    - build

- name: Include task for maps
  include_tasks: "tasks/maps.yml"
  tags:
    - maps

- name: Include task for configuration
  include_tasks: "tasks/configuration.yml"
  tags:
    - configuration

- name: Include task for systemd
  include_tasks: "tasks/systemd.yml"
  tags:
    - systemd

# - name: Include task for database
#   include_tasks: "tasks/database.yml"
#   tags:
#     - database

# Ownership doesn't seem to work?
# - name: Update symlink to the latest release
#   file:
#     src: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}"
#     path: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_server }}"
#     state: link
#     owner: "{{ azerothcore_user }}"
#     group: "{{ azerothcore_user }}"

# - name: Start world- and authserver
#   systemd:
#     state: started
#     enabled: yes
#     name: "{{ item }}"
#     scope: user
#   with_items:
#     - "worldserver"
#     - "authserver"

# - name: Setup backup using cron
#   cron:
#     name: Backup Azerothcore databases
#     minute: "{{ azerothcore_cron_minute }}"
#     hour: "{{ azerothcore_cron_hour }}"
#     job: "cd /home/{{ azerothcore_user }}/{{ azerothcore_folder }}/backup/ && ./backup.sh > /dev/null"
#   when: azerothcore_cron_minute != "" or azerothcore_cron_hour != ""
