---

# TODO
- name: Fetch and download our desired modules
  git:
    repo: "{{ item.git }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/{{ item.name }}"
    version: "{{ item.version }}"
    force: yes
  loop: "{{ azerothcore_modules }}"
  tags:
    - modules
