---

- name: Checkout AzerothCore code
  git:
    repo: "{{ azerothcore_git }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source }}"
    version: "{{ azerothcore_branch }}"
    force: "{{ azerothcore_git_force }}"
  tags:
    - source

- name: Get the latest (short) Git commit tag
  shell: cd "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source }}" && git rev-parse --short=6 $(git rev-parse HEAD)
  register: git_commit_tag
  tags:
    - source

- name: Look for modules
  find:
    paths: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/"
    recurse: no
    file_type: directory
  register: modules_folder
  tags:
    - source

- name: Update modules
  shell: cd "{{ item.path }}" && git pull
  with_items:
    - "{{ modules_folder.files }}"
  when: modules_folder is defined and modules_folder != ""
  tags:
    - source
