---

# Create local user systemd directory
# - name: Make sure user directory exists in local systemd config
#   file:
#     path: "{{ home }}/.config/systemd/user"
#     state: directory
#   tags:
#     - systemd

# Upload our config files
- name: Parse and upload our unit files
  become: true
  template:
    src: "etc/systemd/system/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
  loop:
    - authserver
    - worldserver
  tags:
    - systemd

# Enable the services but keep them stopped: we have to update the database
- name: Enable and STOP both services
  become: true
  systemd_service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
    daemon_reexec: yes
  loop:
    - authserver
    - worldserver
  tags:
    - systemd
