---
#####################
# Folder creation
#####################

- name: Create server log folder
  file:
    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/log"
    state: "directory"
  tags:
    - configuration

#- name: Create config directories
#  file:
#    path: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules"
#    state: directory
#  tags:
#    - configuration

- name: Parse and upload the configuration files
  template:
    src: "acore/etc/{{ item }}.conf"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/{{ item }}.conf"
  loop:
    - worldserver
    - authserver
    - dbimport
  tags:
    - configuration

- name: Parse and upload MODULE configuration files
  template:
    src: "acore/etc/modules/{{ item }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_server_release }}/bin/etc/modules/{{ item }}"
  loop:
    - "playerbots.conf.dist"
    - "challenge_modes.conf.dist"
    - "mod_eluna.conf.dist"
  tags:
    - configuration
