---

- name: Checkout AzerothCore code
  git:
    repo: "{{ azerothcore_git }}"
    dest: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}"
    version: "{{ azerothcore_branch }}"
    force: "{{ azerothcore_git_force }}"
    single_branch: yes
    depth: 1
  tags:
    - source

- name: Look for modules
  find:
    paths: "{{ home }}/{{ azerothcore_folder }}/{{ azerothcore_source_dest_dir }}/modules/"
    recurse: no
    file_type: directory
  register: modules_folder
  tags:
    - source

- name: Update modules
  shell: cd "{{ item.path }}" && git pull
  with_items:
    - "{{ modules_folder.files }}"
  when: modules_folder is defined and modules_folder != ""
  tags:
    - source
