---

- name: Create the database directory
  file:
    path: "{{ sql_dir }}"
    state: directory
  tags:
   - database-init

# Creates the base databases
- name: Upload our SQL files
  template:
    src: "{{ item }}"
    dest: "{{ sql_dir }}/{{ item }}"
  loop:
    - init.sql
    - adhoc.sql
    - realmlist_update.sql
  tags:
   - database-init

- name: Run a raw mysql commands to bootstrap the server
  shell: "mysql -u {{azerothcore_db_user}} --password={{azerothcore_db_password}} < {{ sql_dir }}/init.sql"
  tags:
   - database-init
